nelmio_api_doc:
    documentation:
        info:
            title: VPN Admin
            description: VPN Admin is a simple API that allows to work with users, companies, generate data and provide reports.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
